### ISSUE TITLE
Black screen resuming from sleep

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/game#24]
Black screen resuming from sleep

On my Nexus 5.  Nothing in the logs.  I was at the title screen.

I'm at f2ccf81e5e3ae0f8424c30d82633b8786b0174d1

flutter --version                                                                                                                                                   [/src/game]
Flutter
Repository: git@github.com:flutter/flutter.git
Branch: master
Revision: 64bec53646ca3326681187f447d6d479b1d2c923 (88 minutes ago)

**Comment by eseidelGoogle** [comment]
Probably just https://github.com/flutter/flutter/issues/997

**Comment by vlidholt** [comment]
Seems to be fixed!
