### ISSUE TITLE
Game does accept input after phone turned back on

### ISSUE THREAD

**Issue by sethladd** [flutter/game#32]
On my nexus 6p:

* start the game
* play the game
* get to menu screen
* turn off phone
* turn phone back on
* launch game
* see menu screen
* tap Play button (or any button)

expected:

* Play the game

actual:

* I hear the click, but nothing else happens.

**Comment by sethladd** [comment]
I now see a black screen when I restart the game.

**Comment by vlidholt** [comment]
This is most likely an issue with the engine. Filed a bug here: https://github.com/flutter/flutter/issues/997

**Comment by sethladd** [comment]
Thanks!

**Comment by vlidholt** [comment]
This works for me now
