### ISSUE TITLE
App installs, but but just shows black screen

### ISSUE THREAD

**Issue by spierce7** [flutter/game#60]
The app is installing on my Nexus 5X just fine, but then after it starts up it's just a black screen. I'm using the latest flutter.

![screenshot_20160506-004830](https://cloud.githubusercontent.com/assets/871169/15064623/5309dffe-1324-11e6-98fb-7c48ede665c8.png)

```
spierce7$ flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/spierce7/frameworks/flutter
    • Framework revision 5460e94488 (3 days ago), engine revision 76d5cf230a

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/spierce7/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.7.0_80-b15)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.1
```

**Comment by colin3dmax** [comment]
I have the same problem on iOS
NoSuchMethodError   activity.setSystemUiVisibility(SystemUiVisibility.immersive);

**Comment by spierce7** [comment]
Seems to be fixed on Android for the latests version. Was able to pull and I'm at least seeing the game display now.
